import type {Implant} from "../types/implants.ts";

export const InitialImplants: Implant[] = [
    {
        id: crypto.randomUUID(),
        name: "Sandevistan",
        rarity: "Legendary",
        cost: 39000,
        slot: "Operating System",
        energy: 18,
        manufacturer : "QianT",
    },
    {
        id: crypto.randomUUID(),
        name: "Mantis Blades",
        rarity: "Epic",
        cost: 25000,
        slot: "Arms",
        energy: 12,
        manufacturer : "Arasaka",
    },
    {
        id: crypto.randomUUID(),
        name: "Gorilla Arms",
        rarity: "Rare",
        cost: 15000,
        slot: "Arms",
        energy: 10,
        manufacturer : "Militech",
    },
    {
        id: crypto.randomUUID(),
        name: "Kiroshi Optics MK.3",
        rarity: "Epic",
        cost: 18000,
        slot: "Ocular System",
        energy: 6,
        manufacturer : "Kiroshi",
    },
    {
        id: crypto.randomUUID(),
        name: "Second Heart",
        rarity: "Legendary",
        cost: 42000,
        slot: "Circulatory System",
        energy: 0,
        manufacturer : "Biotechnica",
    },
    {
        id: crypto.randomUUID(),
        name: "Subdermal Armor",
        rarity: "Rare",
        cost: 12000,
        slot: "Integumentary System",
        energy: 4,
        manufacturer : "Zetatech",
    },
    {
        id: crypto.randomUUID(),
        name: "Berserk MK.1",
        rarity: "Uncommon",
        cost: 8000,
        slot: "Operating System",
        energy: 8,
        manufacturer : "Dynalar",
    },
    {
        id: crypto.randomUUID(),
        name: "Reinforced Tendons",
        rarity: "Rare",
        cost: 14000,
        slot: "Legs",
        energy: 5,
        manufacturer : "Zetatech",
    },
    {
        id: crypto.randomUUID(),
        name: "Monowire",
        rarity: "Epic",
        cost: 22000,
        slot: "Arms",
        energy: 11,
        manufacturer : "Arasaka",
    },
    {
        id: crypto.randomUUID(),
        name: "Optical Camo",
        rarity: "Legendary",
        cost: 35000,
        slot: "Integumentary System",
        energy: 14,
        manufacturer : "Militech",
    },
];